#+TITLE: Sorano Project

* Setup
** TODO One step install script
** Install docker on sorano.home
   
   Followed this [[https://docs.docker.com/engine/installation/debian/][Documentation]]

   #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano
     apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
     echo 'deb https://apt.dockerproject.org/repo debian-jessy main' >> /etc/apt/sources.list
     apt-get update
     apt-get install docker-engine
     systemctl enable docker
   #+END_SRC

** Setup salt master docker
   
   Set up dependencies for salt master docker to run
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/srv
      mkdir -p /srv/docker/volumes/saltmaster/etc/salt/pki
      mkdir -p /srv/docker/volumes/saltmaster/var/cache/salt
      mkdir -p /srv/docker/volumes/saltmaster/var/logs/salt
    #+END_SRC

    #+RESULTS:

    These directories are not controlled by the source control. 
    They are only needed to make sure the infor stored there is persisted


*** build the salt master
      #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/soranoProject/docker/salt_master :results raw
      docker build -t vercapi/salt_master .
      #+END_SRC
    
      #+RESULTS:
      Sending build context to Docker daemon  2.56 kBSending build context to Docker daemon  2.56 kB
      Step 1 : FROM debian:jessie
       ---> 91bac885982d
      Step 2 : RUN apt-get update && apt-get install -y wget
       ---> Using cache
       ---> 2fda7ad65f9d
      Step 3 : RUN wget -O - https://repo.saltstack.com/apt/debian/latest/SALTSTACK-GPG-KEY.pub | apt-key add -
       ---> Using cache
       ---> 7b42cadccb6f
      Step 4 : RUN echo deb http://repo.saltstack.com/apt/debian/latest jessie main >> /etc/apt/sources.list
       ---> Using cache
       ---> a13b8e49d623
      Step 5 : VOLUME ['/etc/salt/pki', '/var/cache/salt', '/var/logs/salt', '/etc/salt/master.d', '/srv/salt']
       ---> Using cache
       ---> 05f369ace767
      Step 6 : RUN apt-get update && apt-get install -y salt-master
       ---> Using cache
       ---> 68522807cf86
      Step 7 : EXPOSE 4505 4506
       ---> Using cache
       ---> ef03da46b8d0
      Step 8 : CMD salt-master
       ---> Using cache
       ---> 2cc153c12a64
      Successfully built 2cc153c12a64

*** Starting the saltmaster manually


    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|docker:saltmasterB:/etc
    ls /etc/salt/master
    #+END_SRC

    #+RESULTS:
    : /etc/salt/master

    Start as daemon
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/soranoProject
      docker run -id -h sorano.salt \
      -p 4505:4505 -p 4506:4506 \
      --name saltmaster \
      -v /srv/docker/volumes/saltmaster/etc/salt/pki:/etc/salt/pki \
      -v /srv/docker/volumes/saltmaster/var/cache/salt:/var/cache/salt \
      -v /srv/docker/volumes/saltmaster/var/logs/salt:/var/logs/salt \
      -v /home/sorano/soranoProject/saltstack/master.d:/etc/salt/master.d \
      -v /home/sorano/soranoProject/saltstack/salt:/srv/salt \
      vercapi/salt_master
    #+END_SRC

    #+RESULTS:
    : f29da3b5f45b4805ab2d77391f197401ad6ae062bb62721848d66749502efb18

    Open connection to salt master to see if it is running
    #+BEGIN_SRC sh /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/
    nc -v 127.0.0.1 4506 
    #+END_SRC

    Check running dockers
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/
    docker ps
    #+END_SRC

    Manually stop the maching
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/
    docker stop saltmaster && docker rm saltmaster
    #+END_SRC

    Attach to running machine
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/
    docker exec -it saltmaster bash
    #+END_SRC

*** Set up automatic start

    Copy the file in place, reload configuration and enable the service
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/soranoProject/systemd
      cp saltmaster.service /etc/systemd/system
      systemctl daemon-reload
      systemctl enable saltmaster
    #+END_SRC

    #+RESULTS:

    Start the service manually
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/ :results raw
    systemctl restart saltmaster
    systemctl status saltmaster
    #+END_SRC

    #+RESULTS:
    [1;32mâ—[0m saltmaster.service - Saltmaster for Sorano
       Loaded: loaded (/etc/systemd/system/saltmaster.service; enabled)
       Active: [1;32mactive (running)[0m since Sun 2015-11-29 22:44:15 CET; 7ms ago
      Process: 5715 ExecStop=/usr/bin/docker stop saltmaster (code=exited, status=0/SUCCESS)
     Main PID: 5828 (docker)
       CGroup: /system.slice/saltmaster.service
               â””â”€5828 /usr/bin/docker run -i --rm -h sorano.salt -p 4505:4505 -p ...

** Base minion

*** Build the minion
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/soranoProject/docker/debian_minion :results raw
    docker build -t vercapi/debian_minion .
    #+END_SRC

    #+RESULTS:
    Sending build context to Docker daemon 3.584 kBSending build context to Docker daemon 3.584 kB
    Step 1 : FROM debian:jessie
     ---> 91bac885982d
    Step 2 : RUN apt-get update && apt-get install -y wget
     ---> Using cache
     ---> 2fda7ad65f9d
    Step 3 : RUN wget -O - https://repo.saltstack.com/apt/debian/latest/SALTSTACK-GPG-KEY.pub | apt-key add -
     ---> Using cache
     ---> 7b42cadccb6f
    Step 4 : RUN echo deb http://repo.saltstack.com/apt/debian/latest jessie main >> /etc/apt/sources.list
     ---> Using cache
     ---> a13b8e49d623
    Step 5 : RUN apt-get update && apt-get install -y salt-minion
     ---> Using cache
     ---> b66e3cfd3379
    Step 6 : ADD ./minion /etc/salt/minion
     ---> Using cache
     ---> ed217627d9e9
    Step 7 : VOLUME ['/etc/salt/minion.d', '/etc/salt/pki']
     ---> Using cache
     ---> 70cf8a894c97
    Step 8 : CMD /usr/bin/salt-minion
     ---> Running in 0a75cfc6401c
     ---> 6e47fe99fd16
    Removing intermediate container 0a75cfc6401c
    Successfully built 6e47fe99fd16

    
    

*** Running the minion manually
    This only needs to be run to test. This image is intended as a base image
    
    Start as daemon, after creating the needed directories.
    Directories will not be re-created if they already exist.
    #+NAME: start_minion_docker
    #+HEADER: :var minion_dir='salt_minion'
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/soranoProject
      mkdir -p /home/sorano/soranoProject/saltstack/$minion_dir/etc/salt/minion.d
      mkdir -p /srv/docker/volumes/$minion_dir/etc/salt/pki
      docker run -id -h minion.sorano \
             --name saltminion \
             -v /home/sorano/soranoProject/saltstack/$minion_dir:/etc/salt/minion.d \
             -v /srv/docker/volumes/$minion_dir/etc/salt/pki:/etc/salt/pki \
             vercapi/debian_minion
    #+END_SRC

    #+RESULTS: start_minion_docker
    : 0aa1781a0d9bc314ec38f33b1cfdc7322d297c2cdbe7de4c36ede30283f9132f

    Attach to running machine
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/
      docker exec -it saltminion bash
    #+END_SRC

*** Register minion with master
    
    Check for the keys
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2|docker:saltmaster:/etc/salt
    salt-key -L
    #+END_SRC

    Check the actual key of the minion on the master
    salt-key -f <minion>

    Accept all keys
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2|docker:saltmaster:/etc/salt
    salt-key -A
    #+END_SRC

    Check the actual key of the minion on the minion
    salt-call key.finger --local

* TODO Backup
