#+TITLE: Sorano Project

* Setup

** TODO One step install script

** Install docker on sorano.home
   
   Followed this [[https://docs.docker.com/engine/installation/debian/][Documentation]]

   #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano
     apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
     echo 'deb https://apt.dockerproject.org/repo debian-jessy main' >> /etc/apt/sources.list
     apt-get update
     apt-get install docker-engine
     systemctl enable docker
   #+END_SRC


** Setup salt master docker
   
   Set up dependencies for salt master docker to run
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/srv
      mkdir -p /srv/docker/volumes/saltmaster/etc/salt/pki
      mkdir -p /srv/docker/volumes/saltmaster/var/cache/salt
      mkdir -p /srv/docker/volumes/saltmaster/var/logs/salt
    #+END_SRC

    #+RESULTS:

    These directories are not controlled by the source control. 
    They are only needed to make sure the infor stored there is persisted


*** build the salt master
  
      Build the saltmaster with a ssh password as paramet. The password file is removed from the host and the docker after building the image.
      It should leave no traces.

      #+HEADER: :var ssh_pwd='not-real'
      #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/soranoProject/docker/salt_master :results raw
      echo $ssh_pwd > pwdfile
      docker build -t vercapi/salt_master .
      rm pwdfile
      #+END_SRC
    
      #+RESULTS:
      Sending build context to Docker daemon 37.38 kBSending build context to Docker daemon 37.38 kB
      Step 1 : FROM debian:jessie
       ---> 91bac885982d
      Step 2 : RUN apt-get update && apt-get install -y wget
       ---> Using cache
       ---> 2fda7ad65f9d
      Step 3 : RUN wget -O - https://repo.saltstack.com/apt/debian/latest/SALTSTACK-GPG-KEY.pub | apt-key add -
       ---> Using cache
       ---> 7b42cadccb6f
      Step 4 : RUN echo deb http://repo.saltstack.com/apt/debian/latest jessie main >> /etc/apt/sources.list
       ---> Using cache
       ---> a13b8e49d623
      Step 5 : VOLUME ['/etc/salt/pki', '/var/cache/salt', '/var/logs/salt', '/etc/salt/master.d', '/srv/salt']
       ---> Using cache
       ---> 05f369ace767
      Step 6 : RUN apt-get update && apt-get install -y salt-master
       ---> Using cache
       ---> 68522807cf86
      Step 7 : COPY master /etc/salt/master
       ---> Using cache
       ---> 8b16b5abc3e8
      Step 8 : EXPOSE 4505 4506
       ---> Using cache
       ---> ec4c3fc56e58
      Step 9 : RUN apt-get install -y openssh-server supervisor
       ---> Using cache
       ---> 876016465c5a
      Step 10 : RUN mkdir -p /var/run/sshd
       ---> Using cache
       ---> 54f16bbe39a1
      Step 11 : COPY pwdfile /etc/pwdfile
       ---> 5a5e8ed5a336
      Removing intermediate container d55081c3c474
      Step 12 : RUN echo root:`cat /etc/pwdfile` | chpasswd
       ---> Running in ffb1626e3ec4
       ---> d22c6363fbb3
      Removing intermediate container ffb1626e3ec4
      Step 13 : RUN rm /etc/pwdfile
       ---> Running in 98c44c7a78b0
       ---> c5faad9f1ed3
      Removing intermediate container 98c44c7a78b0
      Step 14 : RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
       ---> Running in e1a85a758437
       ---> 55d460bf392b
      Removing intermediate container e1a85a758437
      Step 15 : ENV NOTVISIBLE "in users profile"
       ---> Running in a3700266f586
       ---> 3ccdf8b7f34f
      Removing intermediate container a3700266f586
      Step 16 : RUN echo "export VISIBLE=now" >> /etc/profile
       ---> Running in d6a5fa7012ee
       ---> 22ac33a72841
      Removing intermediate container d6a5fa7012ee
      Step 17 : RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
       ---> Running in 4b0b1f404622
       ---> e444871d969e
      Removing intermediate container 4b0b1f404622
      Step 18 : EXPOSE 22
       ---> Running in 52bce4b3949f
       ---> b0f1fc8c331e
      Removing intermediate container 52bce4b3949f
      Step 19 : COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
       ---> 6dfc76d30f23
      Removing intermediate container a1283ff627ea
      Step 20 : RUN mkdir -p /var/log/supervisor
       ---> Running in 5f72e5c2ea74
       ---> a1ceec42009b
      Removing intermediate container 5f72e5c2ea74
      Step 21 : CMD /usr/bin/supervisord
       ---> Running in d5e0ff6c4fcc
       ---> 021d00a780dd
      Removing intermediate container d5e0ff6c4fcc
      Successfully built 021d00a780dd
      
                              
*** Starting the saltmaster manually


    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|docker:saltmasterB:/etc
    ls /etc/salt/master
    #+END_SRC

    #+RESULTS:
    : /etc/salt/master

    Start as daemon
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/soranoProject
      docker run -id -h sorano.salt \
      -p 4505:4505 -p 4506:4506 -p 2222:22 \
      --name saltmaster \
      -v /srv/docker/volumes/saltmaster/etc/salt/pki:/etc/salt/pki \
      -v /srv/docker/volumes/saltmaster/var/cache/salt:/var/cache/salt \
      -v /srv/docker/volumes/saltmaster/var/logs/salt:/var/logs/salt \
      -v /home/sorano/soranoProject/saltstack/master.d:/etc/salt/master.d \
      -v /home/sorano/soranoProject/saltstack/salt:/srv/salt \
      vercapi/salt_master
    #+END_SRC

    #+RESULTS:
    : 96a7dcfcc2b9471450660640d43f376e25cca3f5ed55c361de46c1f9f1017b2e

    Open connection to salt master to see if it is running
    #+BEGIN_SRC sh /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/
    nc -v 127.0.0.1 4506 
    #+END_SRC

    Check running dockers
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/
    docker ps
    #+END_SRC

    Manually stop the maching
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/
    docker stop saltmaster && docker rm saltmaster
    #+END_SRC

    Attach to running machine
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/
    docker exec -it saltmaster bash
    #+END_SRC


*** Set up automatic start

    Copy the file in place, reload configuration and enable the service
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/soranoProject/systemd
      cp saltmaster.service /etc/systemd/system
      systemctl daemon-reload
      systemctl enable saltmaster
    #+END_SRC

    #+RESULTS:

    Start the service manually
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/ :results raw
    systemctl restart saltmaster
    systemctl status saltmaster
    #+END_SRC

    #+RESULTS:
    [1;32mâ—[0m saltmaster.service - Saltmaster for Sorano
       Loaded: loaded (/etc/systemd/system/saltmaster.service; enabled)
       Active: [1;32mactive (running)[0m since Sun 2015-11-29 22:44:15 CET; 7ms ago
      Process: 5715 ExecStop=/usr/bin/docker stop saltmaster (code=exited, status=0/SUCCESS)
     Main PID: 5828 (docker)
       CGroup: /system.slice/saltmaster.service
               â””â”€5828 /usr/bin/docker run -i --rm -h sorano.salt -p 4505:4505 -p ...


** Base minion

*** Build the minion
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/soranoProject/docker/debian_minion :results raw
    docker build -t vercapi/debian_minion .
    #+END_SRC

    #+RESULTS:
    Sending build context to Docker daemon 3.584 kBSending build context to Docker daemon 3.584 kB
    Step 1 : FROM debian:jessie
     ---> 91bac885982d
    Step 2 : RUN apt-get update && apt-get install -y wget
     ---> Using cache
     ---> 2fda7ad65f9d
    Step 3 : RUN wget -O - https://repo.saltstack.com/apt/debian/latest/SALTSTACK-GPG-KEY.pub | apt-key add -
     ---> Using cache
     ---> 7b42cadccb6f
    Step 4 : RUN echo deb http://repo.saltstack.com/apt/debian/latest jessie main >> /etc/apt/sources.list
     ---> Using cache
     ---> a13b8e49d623
    Step 5 : RUN apt-get update && apt-get install -y salt-minion
     ---> Using cache
     ---> b66e3cfd3379
    Step 6 : ADD ./minion /etc/salt/minion
     ---> Using cache
     ---> ed217627d9e9
    Step 7 : VOLUME ['/etc/salt/minion.d', '/etc/salt/pki']
     ---> Using cache
     ---> 70cf8a894c97
    Step 8 : CMD /usr/bin/salt-minion
     ---> Using cache
     ---> 6e47fe99fd16
    Successfully built 6e47fe99fd16


*** Running the minion manually
    This only needs to be run to test. This image is intended as a base image
    
    Start as daemon, after creating the needed directories.
    Directories will not be re-created if they already exist.
    #+NAME: start_minion_docker
    #+HEADER: :var minion_dir='minion'
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/soranoProject
      mkdir -p /srv/docker/volumes/$minion_dir/etc/salt/minion.d
      mkdir -p /srv/docker/volumes/$minion_dir/etc/salt/pki
      docker run -id -h minion.sorano \
             --name saltminion \
             -v /srv/docker/volumes/$minion_dir/etc/salt/minion.d:/etc/salt/minion.d \
             -v /srv/docker/volumes/$minion_dir/etc/salt/pki:/etc/salt/pki \
             vercapi/debian_minion
    #+END_SRC

    #+RESULTS: start_minion_docker
    : e046f6e77899ba6b20c14e59168163122356c01f12ed8e5c65b6d834c60e915f

    Attach to running machine
    #+BEGIN_SRC sh :dir /ssh:sorano@192.168.1.2|sudo:192.168.1.2:/home/sorano/
      docker exec -it saltminion bash
    #+END_SRC


*** Register minion with master
    
    Check for the keys
    #+BEGIN_SRC sh :dir /ssh:root@192.168.1.2#2222:/etc/salt :results table
    salt-key -L
    #+END_SRC

    #+RESULTS:
    | [0;1;32mAccepted           | Keys:[0;0m |
    | [0;32msorano.home[0;0m   |              |
    | [0;1;35mDenied             | Keys:[0;0m |
    | [0;1;31mUnaccepted         | Keys:[0;0m |
    | [0;31mminion.sorano[0;0m |              |
    | [0;1;34mRejected           | Keys:[0;0m |

    #+HEADER: :var minion_name='saltminion'
    #+BEGIN_SRC sh :dir /ssh:root@192.168.1.2#2222:/etc/salt
    salt-key -f $minion_name
    #+END_SRC

    Accept all keys
    #+BEGIN_SRC sh :dir /ssh:root@192.168.1.2#2222:/etc/salt
    yes | salt-key -A
    #+END_SRC

    Check the actual key of the minion on the minion
    #+BEGIN_SRC sh :dir /sudo:192.168.1.2:/root
    salt-call key.finger --local
    #+END_SRC

    Remove a key for a minion
    #+HEADER: :var minion_name='saltminion'
    #+BEGIN_SRC sh :dir /ssh:root@192.168.1.2#2222:/etc/salt
    salt-key -d $minion_name
    #+END_SRC


*** Start a docker minion via the master
    
* TODO Backup
